In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

# ========== Data ==========

In [2]:
data = pd.read_csv('dataset2.csv')

In [3]:
data

x1  x2  y
0   0   1  1
1   1   0  2
2  -1   0  3
3   0  -1  4

In [4]:
X = data[['x1', 'x2']]

In [5]:
y = data['y']

# ========== Model ==========

In [6]:
clf = LogisticRegression(penalty='none')
clf.fit(X, y)

LogisticRegression(penalty='none')

In [7]:
clf.intercept_

array([-2.62306367e-08,  2.95335134e-08,  2.54560370e-08, -2.87561552e-08])

In [8]:
clf.coef_

array([[-1.44123650e-09,  1.04728380e+01],
       [ 1.04728380e+01, -8.95380278e-10],
       [-1.04728380e+01, -8.95382812e-10],
       [-1.44123698e-09, -1.04728380e+01]])

# ========== Prediction ==========

In [9]:
X = pd.read_csv('incoming_data.csv')

In [10]:
X

x1   x2
0  0.0  1.5
1  1.5  0.0
2 -1.5  0.0
3  0.0 -1.5

In [11]:
clf.predict(X)

array([1, 2, 3, 4])

In [12]:
clf.predict_proba(X)

array([[9.99999699e-01, 1.50506847e-07, 1.50506847e-07, 2.26523154e-14],
       [1.50506824e-07, 9.99999699e-01, 2.26523135e-14, 1.50506824e-07],
       [1.50506826e-07, 2.26523137e-14, 9.99999699e-01, 1.50506825e-07],
       [2.26523155e-14, 1.50506848e-07, 1.50506848e-07, 9.99999699e-01]])