In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


# ========== Data ==========

In [2]:
data = pd.read_csv("dataset (multi-class).csv")

In [3]:
data

x1    x2  y
0   0.00  1.00  0
1   0.00  1.25  0
2   0.00  1.50  0
3   0.00  1.75  0
4   0.00  2.00  0
5   1.00  0.00  1
6   1.25  0.00  1
7   1.50  0.00  1
8   1.75  0.00  1
9   2.00  0.00  1
10 -1.00  0.00  2
11 -1.25  0.00  2
12 -1.50  0.00  2
13 -1.75  0.00  2
14 -2.00  0.00  2
15  0.00 -1.00  3
16  0.00 -1.25  3
17  0.00 -1.50  3
18  0.00 -1.75  3
19  0.00 -2.00  3

In [4]:
X_train_scaled = data[["x1", "x2"]]

In [5]:
y_train = data["y"]

# ========== Model ==========

## Setting Parameter

In [6]:
clf = LogisticRegression(penalty="none")

## Train Model

In [7]:
clf.fit(X_train_scaled, y_train)

LogisticRegression(penalty='none')

## Model's Weight & Bias

In [8]:
clf.intercept_

array([ 1.93132718e-08, -1.72643302e-08, -1.85838251e-08,  1.64870550e-08])

In [9]:
clf.coef_

array([[-4.93360504e-10,  1.04779162e+01],
       [ 1.04779162e+01, -1.03997446e-09],
       [-1.04779162e+01, -1.03997418e-09],
       [-4.93359781e-10, -1.04779162e+01]])

# ========== Prediction ==========

In [10]:
X_test_scaled = pd.read_csv("incoming_data (multi-class).csv")

In [11]:
X_test_scaled

x1   x2
0  0.0  1.5
1  1.5  0.0
2 -1.5  0.0
3  0.0 -1.5

In [12]:
clf.predict(X_test_scaled)

array([0, 1, 2, 3], dtype=int64)

In [13]:
clf.predict_proba(X_test_scaled)

array([[9.99999701e-01, 1.49364729e-07, 1.49364728e-07, 2.23098305e-14],
       [1.49364744e-07, 9.99999701e-01, 2.23098318e-14, 1.49364744e-07],
       [1.49364745e-07, 2.23098319e-14, 9.99999701e-01, 1.49364744e-07],
       [2.23098307e-14, 1.49364730e-07, 1.49364730e-07, 9.99999701e-01]])