In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

# ========== Data ==========

In [2]:
data = pd.read_csv('dataset.csv')

In [3]:
data

x1  x2  y
0   0   1  1
1   1   0  1
2  -1   0  0
3   0  -1  0

In [4]:
X = data[['x1', 'x2']]

In [5]:
y = data['y']

# ========== Model ==========

In [7]:
clf = LogisticRegression(penalty='none')
clf.fit(X, y)

LogisticRegression(penalty='none')

In [8]:
clf.intercept_

array([0.])

In [9]:
clf.coef_

array([[10.52183855, 10.52183855]])

# ========== Prediction ==========

In [10]:
X = pd.read_csv('incoming_data.csv')

In [11]:
X

x1   x2
0  0.0  1.5
1  1.5  0.0
2 -1.5  0.0
3  0.0 -1.5

In [12]:
clf.predict(X)

array([1, 1, 0, 0])

In [13]:
clf.predict_proba(X)

array([[1.39841254e-07, 9.99999860e-01],
       [1.39841254e-07, 9.99999860e-01],
       [9.99999860e-01, 1.39841254e-07],
       [9.99999860e-01, 1.39841254e-07]])