In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegressionCV

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('dataset4.csv')

In [3]:
data

x1    x2  y
0   0.00  1.00  1
1   0.00  1.25  1
2   0.00  1.50  1
3   0.00  1.75  1
4   0.00  2.00  1
5   1.00  0.00  2
6   1.25  0.00  2
7   1.50  0.00  2
8   1.75  0.00  2
9   2.00  0.00  2
10 -1.00  0.00  3
11 -1.25  0.00  3
12 -1.50  0.00  3
13 -1.75  0.00  3
14 -2.00  0.00  3
15  0.00 -1.00  4
16  0.00 -1.25  4
17  0.00 -1.50  4
18  0.00 -1.75  4
19  0.00 -2.00  4

In [4]:
X = data[['x1', 'x2']]

In [5]:
y = data['y']

# ========== L2 Regularization ==========

In [6]:
alphas = np.logspace(-3, 3, num=100)

In [7]:
clf = LogisticRegressionCV(penalty='l2', Cs=alphas, cv=5)
clf.fit(X, y)

LogisticRegressionCV(Cs=array([1.00000000e-03, 1.14975700e-03, 1.32194115e-03, 1.51991108e-03,
       1.74752840e-03, 2.00923300e-03, 2.31012970e-03, 2.65608778e-03,
       3.05385551e-03, 3.51119173e-03, 4.03701726e-03, 4.64158883e-03,
       5.33669923e-03, 6.13590727e-03, 7.05480231e-03, 8.11130831e-03,
       9.32603347e-03, 1.07226722e-02, 1.23284674e-02, 1.41747416e-02,
       1.62975083e-02, 1.87...
       4.03701726e+01, 4.64158883e+01, 5.33669923e+01, 6.13590727e+01,
       7.05480231e+01, 8.11130831e+01, 9.32603347e+01, 1.07226722e+02,
       1.23284674e+02, 1.41747416e+02, 1.62975083e+02, 1.87381742e+02,
       2.15443469e+02, 2.47707636e+02, 2.84803587e+02, 3.27454916e+02,
       3.76493581e+02, 4.32876128e+02, 4.97702356e+02, 5.72236766e+02,
       6.57933225e+02, 7.56463328e+02, 8.69749003e+02, 1.00000000e+03]),
                     cv=5)

In [8]:
clf.C_

array([0.001, 0.001, 0.001, 0.001])

In [9]:
clf.intercept_

array([ 1.81974603e-19, -7.74629736e-20, -3.32563932e-20, -3.75175543e-19])

In [10]:
clf.coef_

array([[ 1.10066064e-19,  7.45573218e-03],
       [ 7.45573218e-03,  5.48742231e-20],
       [-7.45573218e-03,  5.48742231e-20],
       [ 1.10066064e-19, -7.45573218e-03]])

# ========== L1 Regularization ==========

In [11]:
alphas = np.logspace(-3, 3, num=100)

In [12]:
clf = LogisticRegressionCV(penalty='l1', solver='saga', Cs=alphas, cv=5)
clf.fit(X, y)

LogisticRegressionCV(Cs=array([1.00000000e-03, 1.14975700e-03, 1.32194115e-03, 1.51991108e-03,
       1.74752840e-03, 2.00923300e-03, 2.31012970e-03, 2.65608778e-03,
       3.05385551e-03, 3.51119173e-03, 4.03701726e-03, 4.64158883e-03,
       5.33669923e-03, 6.13590727e-03, 7.05480231e-03, 8.11130831e-03,
       9.32603347e-03, 1.07226722e-02, 1.23284674e-02, 1.41747416e-02,
       1.62975083e-02, 1.87...
       4.03701726e+01, 4.64158883e+01, 5.33669923e+01, 6.13590727e+01,
       7.05480231e+01, 8.11130831e+01, 9.32603347e+01, 1.07226722e+02,
       1.23284674e+02, 1.41747416e+02, 1.62975083e+02, 1.87381742e+02,
       2.15443469e+02, 2.47707636e+02, 2.84803587e+02, 3.27454916e+02,
       3.76493581e+02, 4.32876128e+02, 4.97702356e+02, 5.72236766e+02,
       6.57933225e+02, 7.56463328e+02, 8.69749003e+02, 1.00000000e+03]),
                     cv=5, penalty='l1', solver='saga')

In [13]:
clf.C_

array([0.2009233, 0.2009233, 0.2009233, 0.2009233])

In [14]:
clf.intercept_

array([-2.38946094e-05, -1.80311606e-06,  2.25838229e-05,  3.11390254e-06])

In [15]:
clf.coef_

array([[ 0.        ,  0.44455775],
       [ 0.44457067,  0.        ],
       [-0.44462697,  0.        ],
       [ 0.        , -0.44457305]])

# ========== Elastic Net ==========

In [16]:
alphas = np.logspace(-3, 3, num=100)
l1_ratios = [0.01, 0.05, 0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [17]:
clf = LogisticRegressionCV(penalty='elasticnet', solver='saga', 
                           l1_ratios=l1_ratios, Cs=alphas, cv=5)
clf.fit(X, y)

LogisticRegressionCV(Cs=array([1.00000000e-03, 1.14975700e-03, 1.32194115e-03, 1.51991108e-03,
       1.74752840e-03, 2.00923300e-03, 2.31012970e-03, 2.65608778e-03,
       3.05385551e-03, 3.51119173e-03, 4.03701726e-03, 4.64158883e-03,
       5.33669923e-03, 6.13590727e-03, 7.05480231e-03, 8.11130831e-03,
       9.32603347e-03, 1.07226722e-02, 1.23284674e-02, 1.41747416e-02,
       1.62975083e-02, 1.87...
       7.05480231e+01, 8.11130831e+01, 9.32603347e+01, 1.07226722e+02,
       1.23284674e+02, 1.41747416e+02, 1.62975083e+02, 1.87381742e+02,
       2.15443469e+02, 2.47707636e+02, 2.84803587e+02, 3.27454916e+02,
       3.76493581e+02, 4.32876128e+02, 4.97702356e+02, 5.72236766e+02,
       6.57933225e+02, 7.56463328e+02, 8.69749003e+02, 1.00000000e+03]),
                     cv=5,
                     l1_ratios=[0.01, 0.05, 0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1],
                     penalty='elasticnet', solver='saga')

In [18]:
clf.C_

array([0.00231013, 0.00231013, 0.00231013, 0.00231013])

In [19]:
clf.l1_ratio_

array([0.01, 0.01, 0.01, 0.01])

In [20]:
clf.intercept_

array([-0.00012177,  0.00064012, -0.00152522,  0.00100687])

In [21]:
clf.coef_

array([[ 0.        ,  0.00729882],
       [ 0.00729897,  0.        ],
       [-0.00729926,  0.        ],
       [ 0.        , -0.00729868]])