In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegressionCV

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('dataset3.csv')

In [3]:
data

x1   x2  y
0   1.0  0.0  1
1   1.5  0.0  1
2   2.0  0.0  1
3   0.0  1.0  1
4   0.0  1.5  1
5   0.0  2.0  1
6  -1.0  0.0  0
7  -1.5  0.0  0
8  -2.0  0.0  0
9   0.0 -1.0  0
10  0.0 -1.5  0
11  0.0 -2.0  0

In [4]:
X = data[['x1', 'x2']]

In [5]:
y = data['y']

# ========== L2 Regularization ==========

In [6]:
alphas = np.logspace(-3, 3, num=100)

In [7]:
clf = LogisticRegressionCV(penalty='l2', Cs=alphas, cv=5)
clf.fit(X, y)

LogisticRegressionCV(Cs=array([1.00000000e-03, 1.14975700e-03, 1.32194115e-03, 1.51991108e-03,
       1.74752840e-03, 2.00923300e-03, 2.31012970e-03, 2.65608778e-03,
       3.05385551e-03, 3.51119173e-03, 4.03701726e-03, 4.64158883e-03,
       5.33669923e-03, 6.13590727e-03, 7.05480231e-03, 8.11130831e-03,
       9.32603347e-03, 1.07226722e-02, 1.23284674e-02, 1.41747416e-02,
       1.62975083e-02, 1.87...
       4.03701726e+01, 4.64158883e+01, 5.33669923e+01, 6.13590727e+01,
       7.05480231e+01, 8.11130831e+01, 9.32603347e+01, 1.07226722e+02,
       1.23284674e+02, 1.41747416e+02, 1.62975083e+02, 1.87381742e+02,
       2.15443469e+02, 2.47707636e+02, 2.84803587e+02, 3.27454916e+02,
       3.76493581e+02, 4.32876128e+02, 4.97702356e+02, 5.72236766e+02,
       6.57933225e+02, 7.56463328e+02, 8.69749003e+02, 1.00000000e+03]),
                     cv=5)

In [8]:
clf.C_

array([0.1])

In [9]:
clf.intercept_

array([-1.67197337e-06])

In [10]:
clf.coef_

array([[0.33266821, 0.33267022]])

# ========== L1 Regularization ==========

In [11]:
alphas = np.logspace(-3, 3, num=100)

In [12]:
clf = LogisticRegressionCV(penalty='l1', solver='saga', Cs=alphas, cv=5)
clf.fit(X, y)

LogisticRegressionCV(Cs=array([1.00000000e-03, 1.14975700e-03, 1.32194115e-03, 1.51991108e-03,
       1.74752840e-03, 2.00923300e-03, 2.31012970e-03, 2.65608778e-03,
       3.05385551e-03, 3.51119173e-03, 4.03701726e-03, 4.64158883e-03,
       5.33669923e-03, 6.13590727e-03, 7.05480231e-03, 8.11130831e-03,
       9.32603347e-03, 1.07226722e-02, 1.23284674e-02, 1.41747416e-02,
       1.62975083e-02, 1.87...
       4.03701726e+01, 4.64158883e+01, 5.33669923e+01, 6.13590727e+01,
       7.05480231e+01, 8.11130831e+01, 9.32603347e+01, 1.07226722e+02,
       1.23284674e+02, 1.41747416e+02, 1.62975083e+02, 1.87381742e+02,
       2.15443469e+02, 2.47707636e+02, 2.84803587e+02, 3.27454916e+02,
       3.76493581e+02, 4.32876128e+02, 4.97702356e+02, 5.72236766e+02,
       6.57933225e+02, 7.56463328e+02, 8.69749003e+02, 1.00000000e+03]),
                     cv=5, penalty='l1', solver='saga')

In [13]:
clf.C_

array([0.70548023])

In [14]:
clf.intercept_

array([-2.12106021e-05])

In [15]:
clf.coef_

array([[1.07929014, 1.07925392]])

# ========== Elastic Net ==========

In [16]:
alphas = np.logspace(-3, 3, num=100)
l1_ratios = [0.01, 0.05, 0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [17]:
clf = LogisticRegressionCV(penalty='elasticnet', solver='saga', 
                           l1_ratios=l1_ratios, Cs=alphas, cv=5)
clf.fit(X, y)

LogisticRegressionCV(Cs=array([1.00000000e-03, 1.14975700e-03, 1.32194115e-03, 1.51991108e-03,
       1.74752840e-03, 2.00923300e-03, 2.31012970e-03, 2.65608778e-03,
       3.05385551e-03, 3.51119173e-03, 4.03701726e-03, 4.64158883e-03,
       5.33669923e-03, 6.13590727e-03, 7.05480231e-03, 8.11130831e-03,
       9.32603347e-03, 1.07226722e-02, 1.23284674e-02, 1.41747416e-02,
       1.62975083e-02, 1.87...
       7.05480231e+01, 8.11130831e+01, 9.32603347e+01, 1.07226722e+02,
       1.23284674e+02, 1.41747416e+02, 1.62975083e+02, 1.87381742e+02,
       2.15443469e+02, 2.47707636e+02, 2.84803587e+02, 3.27454916e+02,
       3.76493581e+02, 4.32876128e+02, 4.97702356e+02, 5.72236766e+02,
       6.57933225e+02, 7.56463328e+02, 8.69749003e+02, 1.00000000e+03]),
                     cv=5,
                     l1_ratios=[0.01, 0.05, 0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1],
                     penalty='elasticnet', solver='saga')

In [18]:
clf.C_

array([0.1])

In [19]:
clf.l1_ratio_

array([0.01])

In [20]:
clf.intercept_

array([-0.00032995])

In [21]:
clf.coef_

array([[0.32761286, 0.32764452]])